### ISSUE TITLE
Setup Script does not correctly configure environment

### ISSUE THREAD

**Issue by cowhitley** [MicrosoftLearning/DP-900T00A-Azure-Data-Fundamentals#19]
# Module: Explore Data Analytics in Azure
#### Step: 5

Description of issue

Bash setup script fails to correctly setup the environment. It does not configure the input and output for the stream analytics job, and throws the following errors on deployment.

![image](https://user-images.githubusercontent.com/49291217/204141172-e638522c-9bcd-406c-8878-b3c19134858f.png)

Repro steps:

1. Follow lab steps and deploy the environment with the setup.sh script

**Comment by rcaper** [comment]
@cowhitley : 
@Mihai-Ac tested this with two different subscriptions and in Skillable VM and couldn't reproduce this issue.
