### ISSUE TITLE
failed to download Data migration tool 

### ISSUE THREAD

**Issue by vnvbadri** [MicrosoftLearning/DP-900T00A-Azure-Data-Fundamentals#2]
# Module: 03 Explore non-relational data in Azure
#### Step: 00 Load data using the Cosmos DB Data Migration tool
Description of issue

While trying to download datamigration tool, URL is not working 
https://cosmosdbtools.blob.core.windows.net/datamigrationtool/2019.09.23-1.8.3/dt1.8.3.zip

Couldn't find this tool in any other sites

**Comment by rcaper** [comment]
We are removing references to this tool for the time being.
