### ISSUE TITLE
Module-02 Task-Explore blob storage

### ISSUE THREAD

**Issue by rcy0228** [MicrosoftLearning/DP-900T00A-Azure-Data-Fundamentals#22]
# Module: Explore Azure Storage for non-relational data [Module-02]
#### Step: 10

Description of issue
According to the instructions once we navigate back to the data container it shouldn't be containing the **products** directory as blob storage are virtual, and only exist as part of the path of a blob. however, the directory is still present.
![image](https://user-images.githubusercontent.com/104890759/226334093-4c0e77bf-f21d-4ef9-ba25-8e0755159745.png)

**Comment by rcaper** [comment]
Not repro
![Screenshot 2023-03-20 132735](https://user-images.githubusercontent.com/48692806/226458416-36aac91a-ae27-4f17-80d9-b3cc29c07e98.png)
