### ISSUE TITLE
Getting " msauser not authorized to perform operation VersionShowCommand" when opening database in AzureDataExplorer

### ISSUE THREAD

**Issue by ramakoni1** [MicrosoftLearning/DP-900T00A-Azure-Data-Fundamentals#26]
# Module: 00
#### Step: 06
https://microsoftlearning.github.io/DP-900T00A-Azure-Data-Fundamentals/Instructions/Labs/dp900-05b-stream-synapse-data-explorer.html 
Description of issue
When I try to open the iot-data database I am getting "Principal 'msauser=<username>' is not authorized to perform operation 'VersionShowCommand' on 'https://depool****.wg-*****.kusto.azuresynapse.net:443/'. https://depool****.wg-*****.kusto.azuresynapse.net/;fed=true

Repro steps:

1.
1.
1.

**Comment by Mihai-Ac** [comment]
Hello @ramakoni1 

I went through all the steps and could not reproduce the error.
Can you confirm you have waited for both the dxpool to be deployed (having the **Running** status) and the iot-database sucessfully created.

Have you tried re-creating the resources for the exercise again? 

Best regards,
Mihai

**Comment by ramakoni1** [comment]
Yep, I can confirm that I waited for the dxpool status to be running and db successfully created - will retry later today or tomorrow and probably trying to do a recording of the same and will share. Thank you for looking into this.

Regards.
Ramu.

**Comment by rcaper** [comment]
@ramakoni1  We've reached out to the product group for support, but as a "Preview product" it has no SLA. I will remove from the material for the time being. 

FYI @Mihai-Ac

**Comment by ramakoni1** [comment]
Oh ok - was going to test it out again in the afternoon, but thanks for the update.

**Comment by rcaper** [comment]
[like]  Rosemary Caperton reacted to your message:
________________________________
