### ISSUE TITLE
Creating IoT Hub... unrecognized arguments: cloud-shell-storage-eastus 

### ISSUE THREAD

**Issue by kryshr** [MicrosoftLearning/DP-900T00A-Azure-Data-Fundamentals#29]
# Module: Explore fundamentals of real-time analytics
#### Step: 5 bash setup.sh

Description of issue
~~~
bash setup.sh
~~~
I get the error:  unrecognized arguments: cloud-shell-storage-eastus

Cause of the issue: 
~~~ 
rg=$(az group list --query "[].name" -o tsv); 
~~~
The above command retrieves a list of resources but the subsequent code expected only 1 resource group.

Possible solutions:
1. Use the head command to pick the first output from the list. 
~~~
rg=$(az group list --query "[].name" -o tsv | head -n 1);
~~~
2. Pick the resource group which starts with "learn". 
~~~
rg=$(az group list --query "[?contains(name, 'learn')].name" -o tsv);
~~~

**Comment by rcaper** [comment]
Thank you for bringing this to our attention. We are working on an update.

**Comment by rcaper** [comment]
@kryshr we have pushed an update to the script. 

FYI @Mihai-Ac
