### ISSUE TITLE
Fabric lab

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/DP-900T00A-Azure-Data-Fundamentals#33]
Is there an ETA on the release of the Fabric lab and its integration into the DP-900 courseware + ALH platforms?

The instructions already seem to be available at https://github.com/MicrosoftLearning/DP-900T00A-Azure-Data-Fundamentals/blob/master/Instructions/Labs/dp900-04b-fabric-lake-lab.md, at least in draft form.

**Comment by rcaper** [comment]
@VitalyMCT we are looking to release an update to the ILT content sometime in October, details forthcoming.

**Comment by VitalyMCT** [comment]
Thanks @rcaper
