### ISSUE TITLE
Practice Exam Error

### ISSUE THREAD

**Issue by G8StNik** [MicrosoftLearning/DP-900T00A-Azure-Data-Fundamentals#37]
# Module: 00
#### Step: 00

Description of issue
There is an error in the practice exam.
Repro steps:

1. ![image](https://github.com/MicrosoftLearning/DP-900T00A-Azure-Data-Fundamentals/assets/33614203/417219f4-49a3-4ce3-b190-ce559be36609)

**Comment by rcaper** [comment]
Should have closed this 10.4.23 when submitted to correct team.
