### ISSUE TITLE
Unable to find the markdown files of the learning modules

### ISSUE THREAD

**Issue by andreped** [MicrosoftLearning/DP-900T00A-Azure-Data-Fundamentals#39]
Description of issue:
I observed several issues in the in learning modules that I wanted to propose some edits for.

For AI-900, the modules are available at GitHub (see [here](https://github.com/MicrosoftLearning/AI-900-AIFundamentals/tree/main/instructions)) as markdown files within the repo, but for DP-900 I fail to see where these are hosted. Am I blind or are they hosted elsewhere?

**Comment by andreped** [comment]
I found the first page [here](https://github.com/MicrosoftDocs/learn/blob/main/learn-pr/paths/azure-data-fundamentals-explore-non-relational-data/index.yml). Perhaps the rest is hosted in the same repo as well?

**Comment by rcaper** [comment]
@andreped what is your role, and what are you trying to accomplish with the Learn exercise markdown? That would help me understand what you need to access.
