### ISSUE TITLE
odule 03: Lab 02: Upload, download, and query data in a non-relational data store

### ISSUE THREAD

**Issue by manishrps** [MicrosoftLearning/DP-900T00A-Azure-Data-Fundamentals#4]
# Module: 03
#### Step: 07

Description of issue

The command "azcopy 'docs' 'https://<storage-account-name>.file.core.windows.net/documents/productdocs<SAS-token>' --recursive" is not working fine.

please find the error screenshots here 
![35](https://user-images.githubusercontent.com/55728764/152362221-e76670fb-1a26-4351-8355-61bbbd506cde.png)
![36](https://user-images.githubusercontent.com/55728764/152362759-49775837-cd82-4f14-b54b-7f2c6d18f085.png)
 
Please revert me back as soon as possible!
Thank you 

@gsuttie @JohnPWSharp @GraemeMalcolm @mattmin5 @benjiang65

**Comment by GraemeMalcolm** [comment]
@manishrps  Can you share a link to the lab instruction where you're asked to run this command?

**Comment by rcaper** [comment]
Closing this bug, just tested and can't repro.
