### ISSUE TITLE
Lab 03 - CosmosDB - Sample Data no longer created?

### ISSUE THREAD

**Issue by tylerfarmer1** [MicrosoftLearning/DP-900T00A-Azure-Data-Fundamentals#42]
# Lab/Demo: 03 - Explore Azure Cosmos DB
## Task: View and create items

Description of issue
When you use the "Launch Quick Start" and create the SampleDB, the older versions of this would include some sample data.  Step 2 even says to "Select any of the items in the list to see a JSON representation of the item data."   However, the SampleDB no longer seems to include sample data!   I did this in my own subscription as well as in the lab hoster.

Now it seems there is a "CopilotSampleDb" that does have a lot of data.  My opinion - the lab should change the query so that you query the Copilot database.

Example, you could just run the "Select * from c" to get a bunch of data.  Then you could use the Copilot suggested query of "Show all products that have the word "ultra" in the name of description" and then it auto-generates this query:

-- **Prompt:** Show all products that have the word "ultra" in the name or description
-- **Explanation of query:** Selects the items that contain the case insensitive string 'ultra' in either the name or description.
SELECT * FROM c WHERE CONTAINS(c.name, 'ultra', true) OR CONTAINS(c.description, 'ultra', true)

Anyway, just a thought.,

**Comment by MScalopez** [comment]
Reviewing this issue, will let you know my findings

**Comment by MScalopez** [comment]
@tylerfarmer1, the issue has been fixed on our end and the _Launch Quick Start_ option now generates the sample data again.  No changes are then needed for the lab.  Thank you again for bringing this to our attention.
