### ISSUE TITLE
Nit: suggest Web API PBI connector, not Web

### ISSUE THREAD

**Issue by davidnabram** [MicrosoftLearning/DP-900T00A-Azure-Data-Fundamentals#44]
# Module: DP-900
#### Step: 00

Description of issue
Power BI lab instructions could be improved to say to use the "Web API" connector instead of just "Web". When you select Get Data, it shows "Web Page", which will not load the csv file in as expected if you use it. Needs to be wrapped in Csv.Document, which Web Page won't do without a manual adjustment in the advanced editor, which most people won't figure out.

Repro steps:

1.
1.
1.

**Comment by rcaper** [comment]
@davidnabram I am not sure I understand. The only choice is **Web**, I don't see **Web Page**.

![Power BI Get Data](https://github.com/MicrosoftLearning/DP-900T00A-Azure-Data-Fundamentals/assets/48692806/e2f420bb-e3c8-4a94-9af5-e622d5e14b19)
