### ISSUE TITLE
Unable to start stream analytics job

### ISSUE THREAD

**Issue by LewisGoDeploy** [MicrosoftLearning/DP-900T00A-Azure-Data-Fundamentals#48]
# Module: Explore Stream Analytics 
### Task: 01 

Description of issue
Lab 5 - Explore Azure Stream Analytics
"Start job" button produces error. Happens after following the steps in the guide.

![image](https://github.com/MicrosoftLearning/DP-900T00A-Azure-Data-Fundamentals/assets/114931569/23fdf422-8177-4133-963b-1ad1fa024896)

**Comment by afelix-95** [comment]
While I had the same warning message about diagnostic settings, there were no errors and I was able to start the job normally. @LewisGoDeploy did you get any error messages in Cloud Shell after running `setup.sh` ?

**Comment by afelix-95** [comment]
Closing it as no repro.
