### ISSUE TITLE
Epic fail at the first step, doing 'Explore Azure SQL Database' (dp900-01-sql-lab.md)

### ISSUE THREAD

**Issue by loglux** [MicrosoftLearning/DP-900T00A-Azure-Data-Fundamentals#50]
Summary
Raw Error
ERROR TYPE
Provisioning is restricted in this region. Please choose a different region. For exceptions to this rule please open a support request with Issue type of 'Service and subscription limits'. See https://docs.microsoft.com/en-us/azure/sql-database/quota-increase-request for more details. (Code: ProvisioningDisabled)

**Comment by loglux** [comment]
Remove this guide if students don't have a chance to complete it

**Comment by rcaper** [comment]
@afelix-95 will review this

**Comment by afelix-95** [comment]
Some regions have restricted access for creating new Azure SQL servers and databases. For example, if you choose East US as the region for your server it might not let you deploy the resource, so you need to change the location of your server to another option. For me, West Europe worked, but you can try any other option.
