### ISSUE TITLE
Fail in dp900-02-storage-lab

### ISSUE THREAD

**Issue by loglux** [MicrosoftLearning/DP-900T00A-Azure-Data-Fundamentals#51]
There are only 2 options in choice and I used the one is by default.

The provided location 'eastus2euap' is not available for resource group. List of available regions is 'eastasia,southeastasia,australiaeast,australiasoutheast,brazilsouth,canadacentral,canadaeast,switzerlandnorth,germanywestcentral,eastus2,eastus,centralus,northcentralus,francecentral,uksouth,ukwest,centralindia,southindia,jioindiawest,italynorth,japaneast,japanwest,koreacentral,koreasouth,mexicocentral,northeurope,norwayeast,polandcentral,qatarcentral,spaincentral,swedencentral,uaenorth,westcentralus,westeurope,westus2,westus,southcentralus,westus3,southafricanorth,australiacentral,australiacentral2,israelcentral,westindia'. (Code: LocationNotAvailableForResourceGroup)
Troubleshooting Options

**Comment by loglux** [comment]
the same with the second one. it was the second and last option

ERROR TYPE
The provided location 'centraluseuap' is not available for resource group. List of available regions is 'eastasia,southeastasia,australiaeast,australiasoutheast,brazilsouth,canadacentral,canadaeast,switzerlandnorth,germanywestcentral,eastus2,eastus,centralus,northcentralus,francecentral,uksouth,ukwest,centralindia,southindia,jioindiawest,italynorth,japaneast,japanwest,koreacentral,koreasouth,mexicocentral,northeurope,norwayeast,polandcentral,qatarcentral,spaincentral,swedencentral,uaenorth,westcentralus,westeurope,westus2,westus,southcentralus,westus3,southafricanorth,australiacentral,australiacentral2,israelcentral,westindia'. (Code: LocationNotAvailableForResourceGroup)
Troubleshooting Options

**Comment by loglux** [comment]
Explore Azure Data Lake Storage Gen2
Azure Data Lake Store Gen2 support enables you to use hierarchical folders to organize and manage access to blobs. It also enables you to use Azure blob storage to host distributed file systems for common big data analytics platforms.

Download the [product2.json](https://aka.ms/product2.json?azure-portal=true) JSON file from https://aka.ms/product2.json and save it on your computer in the same folder where you downloaded product1.json previously - you’ll upload it to blob storage later).
In the Azure portal page for your storage account, on the left side, scroll down to the Settings section, and select Data Lake Gen2 upgrade.
In the Data Lake Gen2 upgrade page, expand and complete each step to upgrade your storage account to enable hierarchical namespace and support Azure Data Lake Storage Gen 2. This may take some time.
When the upgrade is complete, in the pane on the left side, in the top section, select Storage browser and navigate back to the root of your data blob container, which still contains the product_data folder.
---
And what can I see on the Storage Browser now:
Network request failed - cannot access storage endpoint

**Comment by loglux** [comment]
"message": "Network request failed - cannot access storage endpoint",    "code": 0,    "details": {      "htmlTemplate": "<p><ul data-bind=\"foreach: causes\"><li><span style=\"word-break: break-word;\" data-bind=\"text:details\"></span>&nbsp;<span style=\"word-break: break-word;\" data-bind=\"wi

again at hte step 


Explore Azure Tables
Azure Tables provide a key/value store for applications that need to store data values, but don’t need the full functionality and structure of a relational database.

In the Azure portal page for your storage container, on the left side, in the Data storage section, select Tables.
On the Tables page, select ＋ Table and create a new table named products.
After the products table has been created, in the pane on the left side, in the top section, select Storage browser.

**Comment by rcaper** [comment]
@afelix-95 will review this issue, thank you @loglux.

**Comment by afelix-95** [comment]
I was able to complete the lab without any issues. It might have been a temporary connection problem. Closing it as not reproducible.
