### ISSUE TITLE
Lab Issue - Explore data analytics in Microsoft Fabric

### ISSUE THREAD

**Issue by tylerfarmer1** [MicrosoftLearning/DP-900T00A-Azure-Data-Fundamentals#53]
Module: 4
Lab/Demo: Explore Data Analytics in Microsoft Fabric
Exercise: Ingest Data
Step: 4
Description of issue:

This appears to be a problem with Microsoft Fabric, not really a Lab problem, but I'm not sure.

In this lab, the student is trying to import some sample data called the "Retail Data Model from Wide World Importers." However, when you click on any of the same tables (such as the dimention_stock_item table), you get an error about permissions. Attached is a screen shot of the error.

![Screenshot 2024-07-17 132938](https://github.com/user-attachments/assets/b2f67266-fde2-4121-96a7-3c721bc587db)

It does this with Any table in the Retail Data Model sample tables. If you pick other sample data, such as Diabetes or Covid, those work and you can select data. There's just something "off" with the Retail Sample data.

**Comment by rcaper** [comment]
Thank you @tylerfarmer1,
@afelix-95 can you please review this lab and see if you have the same issue?

**Comment by GraemeMalcolm** [comment]
I can repro this - it does indeed seem to be an issue with the Fabric service itself. I've reported it to the product team. If there's no resolution by tomorrow, I'll update the lab to use a different sample.

**Comment by GraemeMalcolm** [comment]
Resolved by using a differen sample
