### ISSUE TITLE
Explore fundamentals of data visualization with Power BI: Out of date pre-requisite?

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/DP-900T00A-Azure-Data-Fundamentals#54]
The following pre-requisite seems to be out of date. I believe it can be removed.

![image](https://github.com/user-attachments/assets/3759e6df-a91a-49a7-b194-db09b5eeae64)

**Comment by afelix-95** [comment]
You're right! This lab does not use any resource from Azure Portal so that requirement is not needed. Fixed now.

**Comment by VitalyMCT** [comment]
Thanks @afelix-95 !
